//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package  {
	import com.adamatomic.flixel.*;
	
	public class MapMoonshine extends MapBase {
		//Media content declarations
		[Embed(source="MapCSV_Moonshine_Ground.txt", mimeType="application/octet-stream")] public var CSV_Ground:Class;
		[Embed(source="map-tiles.png")] public var Img_Ground:Class;

		
		public function MapMoonshine() {

			_setCustomValues();

			bgColor = 0xffffffff;

			layerGround = new FlxTilemap(new CSV_Ground, Img_Ground,1,1);
			layerGround.x = 0;
			layerGround.y = 0;
			layerGround.scrollFactor.x = 1.000000;
			layerGround.scrollFactor.y = 1.000000;

			allLayers = [ layerGround ];


			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 160;
			boundsMaxY = 160;
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
